/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _3 from './DaoMembers.types';
import * as _4 from './DaoMembers.client';
import * as _5 from './DaoMembers.react-query';
import * as _6 from './DaoMultisig.types';
import * as _7 from './DaoMultisig.client';
import * as _8 from './DaoMultisig.react-query';
import * as _9 from './Governance.types';
import * as _10 from './Governance.client';
import * as _11 from './Governance.react-query';
import * as _12 from './Identityservice.types';
import * as _13 from './Identityservice.client';
import * as _14 from './Identityservice.react-query';
export namespace contracts {
  export const DaoMembers = { ..._3, ..._4, ..._5 };
  export const DaoMultisig = { ..._6, ..._7, ..._8 };
  export const Governance = { ..._9, ..._10, ..._11 };
  export const Identityservice = { ..._12, ..._13, ..._14 };
}
